language: emacs-lisp
sudo: required
cache: apt
env:
  - EVM_EMACS=emacs-25.1-travis
before_install:
  - sudo apt-get install -y nodejs
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
install:
  - cask install
script:
  - emacs --version
  - ./run-lint.sh
  - ./run-tests.sh
